### ISSUE TITLE
couldn't complie on aarch64 platform

### ISSUE THREAD

**Issue by lkkey80** [owt5008137/libcopp#10]
CMake Error at src/libcopp/CMakeLists.txt:14 (add_library):
  Cannot find source file:

/root/test/libcopp-1.2.1/src/libcopp/fcontext/asm/jump_aarch64_sysv_elf_gas.S

**Comment by owt5008137** [comment]
I only implement the platforms detector for s86/x86_64/amd64. You can add `-DLIBCOPP_FCONTEXT_OS_PLATFORM=arm64` to switch to aarch64 toolchains, **ABI** , **binary format** and **ASM tools** will be set automatically.
