### ISSUE TITLE
请问现在全线支持mips 和arm架构吗？

### ISSUE THREAD

**Issue by a996892212** [owt5008137/libcopp#11]
RT. 另外我想问题对内核版本和其他环境的依赖。

**Comment by owt5008137** [comment]
@a996892212 
没有测试mips和arm架构。底层上下文切换用的是boost.context ，它支持就应该支持。如果自动检测脚本不完善可以通过手动指定 ```-DLIBCOPP_FCONTEXT_OS_PLATFORM=``` ,  ```-DLIBCOPP_FCONTEXT_ABI=``` ,  ```-DLIBCOPP_FCONTEXT_BIN_FORMAT=``` ,  ```-DLIBCOPP_FCONTEXT_AS_TOOL=``` ,  ```-DLIBCOPP_FCONTEXT_AS_OUTPUT_SUFFIX=``` 来手动指定。 详见: https://github.com/owt5008137/libcopp/blob/v2/src/libcopp/fcontext/detect/fcontext.detect.cmake

依赖cmake 3.7+，后面会升级到 cmake 3.12+
编译器依赖 gcc 4.4+（以后可能会升级到c++11的最小全功能支持版本，4.7.2+）或clang 3.4+或MSVC 12+(以后可能会升级到MSVC 14+)
系统内核版本最老的测试过的版本是centos 6.2 自带的版本。没有其他要求

**Comment by owt5008137** [comment]
@a996892212 你好，这个问题没有后续需要支持的话我关掉了？

**Comment by opt-liang** [comment]
类go语言编程c++库，支持类go方式协程，跨平台，支持arm、x86、amd64架构，支持window、linux、mac
https://github.com/idealvin/coost

**Comment by owent** [comment]
> 类go语言编程c++库，支持类go方式协程，跨平台，支持arm、x86、amd64架构，支持window、linux、mac
> https://github.com/idealvin/coost

类go的协程库比较成熟的已经有libgo了。这类带runtime的方案不太适合作为中间件的。

**Comment by opt-liang** [comment]
好像没有带runtime吧



---原始邮件---
发件人: "WenTao ***@***.***&gt;
发送时间: 2022年10月18日(周二) 晚上11:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [owent/libcopp] 请问现在全线支持mips 和arm架构吗？ (#11)




  
类go语言编程c++库，支持类go方式协程，跨平台，支持arm、x86、amd64架构，支持window、linux、mac
 https://github.com/idealvin/coost
  
类go的协程库比较成熟的已经有libgo了。这类带runtime的方案不太适合作为中间件的。

**Comment by owent** [comment]
> 好像没有带runtime吧
> […](#)
> ---原始邮件--- 发件人: "WenTao ***@***.***&gt; 发送时间: 2022年10月18日(周二) 晚上11:34 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [owent/libcopp] 请问现在全线支持mips 和arm架构吗？ (#11) 类go语言编程c++库，支持类go方式协程，跨平台，支持arm、x86、amd64架构，支持window、linux、mac https://github.com/idealvin/coost 类go的协程库比较成熟的已经有libgo了。这类带runtime的方案不太适合作为中间件的。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

没有runtime，类似 `wait(XXX)` 这类的接口如何切回的？这个调度层就是runtime

**Comment by opt-liang** [comment]
co 协程库在 linux, mac, windows 等平台，分别基于 epoll, kqueue, iocp 实现。

co 协程库中 context 切换相关的代码，取自 ruki 的 tbox，而 tbox 则参考了 boost 的实现！

https://coostdocs.gitee.io/cn/co/coroutine/

**Comment by opt-liang** [comment]
https://cloud.tencent.com/developer/article/1563253

**Comment by opt-liang** [comment]
都挺好的，如果能够非常方面跨平台的话就更完美了。感谢大佬们开源的项目。

**Comment by owent** [comment]
> co 协程库在 linux, mac, windows 等平台，分别基于 epoll, kqueue, iocp 实现。
> 
> co 协程库中 context 切换相关的代码，取自 ruki 的 tbox，而 tbox 则参考了 boost 的实现！
> 
> https://coostdocs.gitee.io/cn/co/coroutine/

对，这个基于 epoll, kqueue, iocp 实现和boost的asio其实都属于runtime中的IO调度部分。因为很多框架自带调度模型，所以如果作为一个中间件的话，是不太适合要求框架引入其他外部的runtime的。因为如果每个组件都这么搞，那么对于框架层来说就没法去整体管理资源和控制风险。

比如说 Rust中几种runtime实现，很多兼容一个流行的IO库Tokio，就是把Tokio的runtime绑进去，胶水在一起。Rust的这类生态型态差异不大而且都在像Tokio的模式靠拢，所以胶水几个还好还稍微可控一些。像C++各种方案差异巨大的就不太适合这么做。

如果说从框架层入手集成某一种runtime，那直接集成在里面的协程肯定是能做更多事情。比如 libgo 和 libco 都是做了socket接口hook的，libcopp就没做。
