### ISSUE TITLE
vs2019编译会产生错误：libcopp-2\build_jobs_vs2019\x64\DebugALL_BUILD 拒绝访问

### ISSUE THREAD

**Issue by szza** [owt5008137/libcopp#13]

**Comment by owt5008137** [comment]
@szza 可否提供下你的操作系统环境，更详细的vs2019的编译器版本信息和cmake的执行命令？

**Comment by szza** [comment]
> @szza 可否提供下你的操作系统环境，更详细的vs2019的编译器版本信息和cmake的执行命令？

系统是win10-1909，我分别在 intel的i7-8700 和 AMD的R7-4800u上编译过，工具都是 vs2019，.是直接执行这个项目中的 bat文件

**Comment by owt5008137** [comment]
@szza 请问你的VS2019是最新版的的编译器吗？
![](https://i.bmp.ovh/imgs/2020/05/ee228cd601015541.png)
比如我这里的是目前最新的14.25版本，对应MSVC 1925。
![image.png](https://i.loli.net/2020/05/18/13txsipq4ZBnejC.png)
对应组件是MSVC v142 (v14.25)

**一般情况下，拒绝访问之类的错误多半是文件访问权限问题或者Windows下被锁了，试试把 ```build_jobs_vs2019``` 目录完全删掉然后重新跑能否正常呢？**

**Comment by szza** [comment]
@owt5008137  看了下 MSVC 信息和你图中的一致。点击 运行`cmake_dev.bat` 是没有问题的，但是用vs打开生产的编译信息文件`build_jobs_vs2019`里的`run_sample.vcxproj`，运行，最后会出现这个错误，但是exe文件生产了，也能运行。只是调试不了，运行调试也会出现这个错误

**Comment by owt5008137** [comment]
@szza run_sample是个虚拟的target,它是用来一键调用所有的sample的可执行程序的，并不能直接拿来调试。实际可运行的sample是 ```libcopp_sample_*``` 的TARGET。 然后```libcopp_sample_benchmark_*``` 的是用来做压测的有启动参数的

**Comment by owt5008137** [comment]
@szza 你好，这个问题如果解决了的话，我关掉了？
