### ISSUE TITLE
请问要把一个对象附着到协程上, 应该怎么做?

### ISSUE THREAD

**Issue by comealong** [owt5008137/libcopp#14]
协程创建时要调用这个对象的构造函数, 协程退出时要调用这个对象的析构函数.
我看了半天, 没找到示例, 看源代码, 感觉要实现这种功能好像并不容易.

**Comment by owt5008137** [comment]
要自定义action对象。然后action对象里可以自由操作。建议是start的private data参数传入数据，在operator()开始的时候创建自定义的对象构造;也可以在action的构造函数里直接创建。然后action释放的时候析构。

https://github.com/atframework/atsf4g-co/blob/sample_solution/src/server_frame/logic/action/task_action_player_logout.cpp
https://github.com/atframework/atsf4g-co/blob/sample_solution/src/server_frame/dispatcher/cs_msg_dispatcher.cpp#L183

这里有一些参考

**Comment by comealong** [comment]
建议提供更简单合理的接口, 毕竟是很常见的需求

> 要自定义action对象。然后action对象里可以自由操作。建议是start的private data参数传入数据，在operator()开始的时候创建自定义的对象构造;也可以在action的构造函数里直接创建。然后action释放的时候析构。
> 
> https://github.com/atframework/atsf4g-co/blob/sample_solution/src/server_frame/logic/action/task_action_player_logout.cpp
> https://github.com/atframework/atsf4g-co/blob/sample_solution/src/server_frame/dispatcher/cs_msg_dispatcher.cpp#L183
> 
> 这里有一些参考

**Comment by comealong** [comment]
我自定义了一个action对象, 构造析构函数是调了, 但是我发现我不能访问这个action对象, 

> 要自定义action对象。然后action对象里可以自由操作。建议是start的private data参数传入数据，在operator()开始的时候创建自定义的对象构造;也可以在action的构造函数里直接创建。然后action释放的时候析构。
> 
> https://github.com/atframework/atsf4g-co/blob/sample_solution/src/server_frame/logic/action/task_action_player_logout.cpp
> https://github.com/atframework/atsf4g-co/blob/sample_solution/src/server_frame/dispatcher/cs_msg_dispatcher.cpp#L183
> 
> 这里有一些参考

**Comment by owt5008137** [comment]
可以用闭包的哈，比如README的sample里有个示例。

```cpp
typedef cotask::task<> my_task_t;
task_ptr_type co_task = my_task_t::create([]() {
    // 可以在这里定义自己的数据成员的构造和析构的
    std::cout << "task " << cotask::this_task::get<my_task_t>()->get_id() << " started" << std::endl;
    cotask::this_task::get_task()->yield();
    std::cout << "task " << cotask::this_task::get<my_task_t>()->get_id() << " resumed" << std::endl;
    return 0;
});
```

设计上是故意规避task访问action的，因为在某些需要优化的场景里，在coroutine context这一层action是可以复用共享的。而且不同类型的action封装它的对象大小、数据内容都不一样。而且后续我可能会有一些优化策略导致数据结构或者布局变更。```get_raw_action()``` 这个接口是用来单元测试的，我后面可能会打 **deprecated** 标记，目前只有注释里写了。

另外task的接口是可以直接传仿函数、成员函数和普通函数的。如果编译器环境支持的话，仿函数会调用move构造转移进栈空间。

**Comment by comealong** [comment]
谢谢!

那我这种需求该怎么实现呢?
我现在需要可以自动调用自定义的附加对象的构造与析构函数, 并且, 最重要的是, 我能访问这个对象. 
我按你说的方法, 现在遇到的问题就是我无法访问自定义的对象,. get_raw_action返回后, 得到task_action_functor 之后, functor_ 是私有成员. 无法访问.

> 可以用闭包的哈，比如README的sample里有个示例。
> 
> ```c++
> typedef cotask::task<> my_task_t;
> task_ptr_type co_task = my_task_t::create([]() {
>     // 可以在这里定义自己的数据成员的构造和析构的
>     std::cout << "task " << cotask::this_task::get<my_task_t>()->get_id() << " started" << std::endl;
>     cotask::this_task::get_task()->yield();
>     std::cout << "task " << cotask::this_task::get<my_task_t>()->get_id() << " resumed" << std::endl;
>     return 0;
> });
> ```
> 
> 设计上是故意规避task访问action的，因为在某些需要优化的场景里，在coroutine context这一层action是可以复用共享的。而且不同类型的action封装它的对象大小、数据内容都不一样。而且后续我可能会有一些优化策略导致数据结构或者布局变更。`get_raw_action()` 这个接口是用来单元测试的，我后面可能会打 **deprecated** 标记，目前只有注释里写了。
> 
> 另外task的接口是可以直接传仿函数、成员函数和普通函数的。如果编译器环境支持的话，仿函数会调用move构造转移进栈空间。

**Comment by comealong** [comment]
我再详细描述一下我的需求:

我需要把一个对象附加到一个协程上, 并且在协程结束时, 析构该对象. 而且,我在要任何时候都能访问这个对象.
按你说的方法, 我自定义了一个action对象, 确实可以做到协程结束时析构附加对象. 但是我没有任何常规的途径访问这个对象. 我定义这个对象当然是为了访问, 对吧?

**Comment by owt5008137** [comment]
我的意思是说action是一个底层的接口，操作起来是比较麻烦的。如果你要在协程过程中自由访问自己的对象，并且想要简单的使用方式，你可以直接用lambda的接口或者仿函数的接口。cotask里会把传入的lambda或者仿函数转换成底层的action的，你可以不关心action这一层。传入的仿函数和lambda对象的生命周期是自动会跟随action的（也就是会执行完以后自动析构）。至于怎么访问，完全可以自定义的。比如仿函数的例子：


```cpp
struct custom_data {
    template<class ... TARGS>
    custom_data(TARGS... &&) {}
};

struct custom_functor {
    std::shared_ptr<custom_data > custom_data_;
    template<class ... TARGS>
    custom_functor(TARGS... && args): custom_data_(std::make_shared<custom_data>(std::forward<TARGS>(args)...)) {} // 这里创建私有数据对象
    int operator()(void* start_data) {
        // 这里是写成开始后执行的入口
        // 这里可以自由访问自定义数据custom_data_
        return 0;
    }
};

typedef cotask::task<> my_task_t;
task_ptr_type co_task = my_task_t::create(custom_functor(.构造含糊参数...));
co_task->start(自定义start_data，会传入operator()中);
```

上一条回复的lambda是最简单的调用形式。比如:

```cpp
struct custom_data {
    template<class ... TARGS>
    custom_data(TARGS... &&) {}
};

std::shared_ptr<custom_data > custom_data = std::make_shared<custom_data>(构造含糊参数...);
typedef cotask::task<> my_task_t;
task_ptr_type co_task = my_task_t::create([custom_data](void* start_data) {
    // 这里是写成开始后执行的入口
    // 这里面也能自由访问自定义数据 custom_data
    return 0;
});
co_task->start(自定义start_data，会传入上面的参数中);
```

```void* start_data``` 是可以神略的。省略的情况默认是nullptr

**Comment by comealong** [comment]
问题是我需要在外面有这个co_task指针的地方访问这个自定义数据, 并不是只在协程函数里.

**Comment by owt5008137** [comment]
协程函数里有 this_task 接口可以获取到当前执行的task。

外面要访问的话直接外面创建 ```std::shared_ptr<custom_data>``` 传入协程就好了呀。外面还是可以访问这个 ```std::shared_ptr<custom_data>``` 的呀。

**Comment by comealong** [comment]
> 协程函数里有 this_task 接口可以获取到当前执行的task。
> 
> 外面要访问的话直接外面创建 `std::shared_ptr<custom_data>` 传入协程就好了呀。外面还是可以访问这个 `std::shared_ptr<custom_data>` 的呀。

外面通过co_task指针是不能访问custom_data, 我前面讲过原因了, 如果你是指通过我自已保存的指针去访问, 那就使问题复杂化了, 我得在自已在别外保存custom_data, 并且保存 co_task与 custom_data的关联. 这明显是多余重复的工作. 

算了, 其实改改你的代码很容易实现. 我是怕你以后会升级, 改过的代码出现冲突...算了, 先改吧

**Comment by owt5008137** [comment]
还有个方法是创建task的时候可以指定一个预留private data的大小。然后创建完协程以后会预留一定大小的二进制buffer块。这里面也可以存任意的二进制数据或者自定义POD数据类型，也可以通过这个东西和外面交换数据。但是设计模式上是不推荐这么做的，因为这样会导致线程安全的设计更困难。你看看是否满足你的需要呢？

```cpp
struct custom_data {
    template<class ... TARGS>
    custom_data(TARGS... &&) {}
};

struct custom_ref_data {
    custom_data* ref;
};

std::shared_ptr<custom_data > custom_data = std::make_shared<custom_data>(构造函数参数...);
typedef cotask::task<> my_task_t;
task_ptr_type co_task = my_task_t::create([custom_data](void* start_data) {
    assert(cotask::this_task::get<my_task_t>()->get_private_buffer_size() == sizeof(custom_ref_data));
    ((custom_ref_data*)cotask::this_task::get<my_task_t>()->get_private_buffer())->ref = custom_data.get();
    // 这里是写成开始后执行的入口
    // 这里面也能自由访问自定义数据 custom_data
    return 0;
},
0, // 第一个参数是栈大小，填0使用默认值
sizeof(custom_ref_data)
);

// 然后外层也可以通过get_private_buffer()来访问里面的数据
assert(((custom_ref_data*)co_task->get_private_buffer())->ref == custom_data.get());
```
