### ISSUE TITLE
在task_impl类中怎么没有 一个get_id()的接口

### ISSUE THREAD

**Issue by aengusjiang** [owt5008137/libcopp#15]
在task_impl类中怎么没有 一个get_id()的接口？

**Comment by owt5008137** [comment]
@aengusjiang 因为之前id的类型不是固定的，task_impl里不管理id和id分配器。不过现在id的类型固定不允许修改了，后面可以考虑移入task_impl。

**Comment by owt5008137** [comment]
id管理已移入task_impl,我提交到了dev和master分支

**Comment by aengusjiang** [comment]
OK, thanks.
