### ISSUE TITLE
无效的开关PROJECT_DISABLE_MT说明

### ISSUE THREAD

**Issue by aengusjiang** [owt5008137/libcopp#16]
文档中说多线程支持的开关PROJECT_DISABLE_MT， 但是在构建脚本中没有看到
但是有个锁的开关LIBCOPP_DISABLE_ATOMIC_LOCK, 是不是一回事？

**Comment by owt5008137** [comment]
重命名漏改文档了，多线程支持相关的选项是 ```LIBCOPP_DISABLE_THIS_MT``` 和 ```LIBCOPP_DISABLE_ATOMIC_LOCK``` 这两个选项。前者是关闭TLS，后者是关闭atomic，使用普通版本的int操作。

不过不太建议关，影响很小。

**Comment by owt5008137** [comment]
Fix in [1.3.2](https://github.com/owt5008137/libcopp/releases/tag/1.3.2)
