### ISSUE TITLE
协程栈的大小的问题

### ISSUE THREAD

**Issue by aengusjiang** [owt5008137/libcopp#17]
你好, 
      OWenT, 协程栈的大小代码中使用最小的是64KB。这个看了代码发现这主要是跟min_stack size 和max_stack_size有关，而且对对齐了内存管理的page size. 这个大小有点大， 如果是10w个协程的话，需要6250Mb内存. 如果最小的栈大小过大的话， 很可能导致大量的内存浪费.

**Comment by owt5008137** [comment]
@aengusjiang 协程栈的大小是可以通过参数自定义的，要求对齐到4K，最小是8KB哈，64KB是默认值。
另外只要不是malloc的栈分配器，内存在实际使用前虚拟地址是没有映射到物理内存的，malloc分配器不好预估。
如果真的物理内存映射使用到了这么多说明你的业务实际就是需要这么多内存，而且是可以走交换区的。如果要减少内存占用或者交换区的消耗也需要业务侧去限制并发数。

**Comment by aengusjiang** [comment]
ok, 我之前用了stack pool,  跟了一下代码发现stack pool allocate的时候ignore了stack size, 是我用错了, 我在用stack_pool之前设置了stack_size 就ok了
