### ISSUE TITLE
error: ‘xx’ is not a member of ‘xxx {aka xxx}’

### ISSUE THREAD

**Issue by aengusjiang** [owt5008137/libcopp#18]
使用task action，写一个自定义的action 类
class ThenTaskAction1
{
public:
    ThenTaskAction1(){}

    int operator()(void*)
    {
        return 0;
    }
private:
};

然后调用copp_task的then方法：
  using simple_task_t = cotask::task<>;
  auto co_task = simple_task_t::create([]()
            {
            });
        if (nullptr != co_task)
        {
            co_task->start();
            //auto then_ptr1 = co_task->then(ThenTaskAction1());          // build OK

           ThenTaskAction1 tmp;
            auto then_ptr2 = co_task->then(tmp);                                 // 错误: ThenTaskAction1没有operator()成员 
        }
        else
            printf("error create coroutine %d\n", i);

我这边跟踪了一下原因是后面一种调用在模板参数类型是ThenTaskAction1&， 然而前者解释模板参数类型是ThenTaskAction1
于是我这边的解决方式是
在task_actions.h:91行改成
    virtual int operator()(void *priv_data) {
            return detail::task_action_functor_check::call(&std::remove_reference<value_type>::type::operator(), functor_, priv_data);
        }
去掉了引用

看一下大神有什么好的解决方式或者有什么见解

**Comment by owt5008137** [comment]
@aengusjiang 感谢反馈。这里确实是有个bug。开启右值的分支里对类型的推断有问题。
需要构造函数里适配一下，否则生命周期的维护有问题。我明天修复一下

**Comment by owt5008137** [comment]
@aengusjiang  Fixed in [1.3.2](https://github.com/owt5008137/libcopp/releases/tag/1.3.2)
