### ISSUE TITLE
我想利用Task做同步rpc,创建很多Task是不是会有性能损耗

### ISSUE THREAD

**Issue by wangqiangnpq** [owt5008137/libcopp#19]
没有找到一个基于TaskManager的Taskpool的功能，例子里面全是固定申请多少个Task。

**Comment by owt5008137** [comment]
@wangqiangnpq 大批量的压力测试参见这里 https://owent.net/2019/1911.html
这里的压力测试里最多是30000个协程。再多的话可能得考虑一下mmap得数量限制。

task pool是没有意义的。使用stack pool就可以了。使用stack pool以后task的创建/销毁可以支撑到单CPU，QPS 100万以上。基本上不会成为业务的性能瓶颈了。
