### ISSUE TITLE
不错啊。不知道和libgo比较，哪个好一些？

### ISSUE THREAD

**Issue by skyformat99** [owt5008137/libcopp#5]
和libgo比较，哪个方便更好用啊？
谢谢大牛提供好库

**Comment by owt5008137** [comment]
你要容易上手的话，肯定libgo更简单一些。我这个主要还是实现了协程管理和相关资源管理（主要是栈管理）的东西。libgo还实现了很多系统函数的hook，还有线程池之类。如果你说的好用指这个的话，应该是libgo更好用吧。

我不想在这个库里做太多和协程关系不大的事。

**Comment by skyformat99** [comment]
谢谢回答。
