### ISSUE TITLE
请问支持多线程执行task？

### ISSUE THREAD

**Issue by bigbao9494** [owt5008137/libcopp#8]
请问支持多线程执行task？
如果支持，多线程间可以进行task调度？(就是task在不同线程间移动)

**Comment by owt5008137** [comment]
@bigbao9494 API是线程安全的，多个线程同时调用start/resume的话只有一个会返回0，另一个会返回 ```copp::COPP_EC_IS_RUNNING``` 。一个task只能被一个线程 **持有** ， 你可以在你的线程池里直接调用 start/resume 接口，这样哪个线程 **抢占** 到了这个task就是哪个线程在执行。

**Comment by bigbao9494** [comment]
感谢回复，@owt5008137
比如我的task如下(伪代码)：
void task1()
{
    for(;;)
    {
          //do some need 10 ms
          yield;
    }
}
这个task被线程1抢占后它永远都只会在线程1中执行，不能被动态地移动到线程2中去执行
如果这样的话，假设线程1中出现了一个task非常耗时，那么属于这个线程的其它task可能
长时间不会被执行，再假设其它线程2，3，4的task不耗时，一段时间后它们中的task都被
执行完了(task结束了)，这时就会出现不均衡状态：线程1很繁忙而且还有task在等待，线程2
3，4空闲中。这种情况如何解决？

**Comment by owt5008137** [comment]
yield之后线程1就释放出执行权了，这时候线程2去resume就可以转移到线程2执行剩下的代码的。
@bigbao9494

**Comment by bigbao9494** [comment]
感谢回复，@owt5008137
还是继续用这个示例吧，比如我的task如下(伪代码)：
void task1()
{
for(;;)
{
//do some need 10 ms
yield;
}
}
问题：
现在使用2个物理线程来执行协程，如果task1在第一次被执行的时候是在线程1中，
task1可以不可以在一段时间后被调度到线程2中去执行（也许线程1在执行其它
task时造成它很繁忙，这时线程2空闲状态，可以把task1放到线程2去执行）
其实就是已经被一个线程执行过的协程是否可以被放到其它线程中去执行
因为这样是相关栈的context夸线程了。

**Comment by owt5008137** [comment]
@bigbao9494 
可以呀，**线程1** 在执行完一段逻辑之后把 ```task1->yield(nullptr)``` 出去，然后可以去执行其它代码了。这时候 **线程2** 如果空闲的话执行 ```task1->resume(nullptr)``` 。这样 ```task1``` 就在 **线程2** 里继续执行了。

**Comment by bigbao9494** [comment]
@owt5008137
这样好像是不行的，用的boost中的栈切换实现，我写过代码测试过
这种状态，当task1在线程2中恢复栈时会出错的。不知道你有没有
测试过这种情况。

**Comment by owt5008137** [comment]
@bigbao9494 按boost.context的实现来说，它本身是不提供线程安全的功能的。但是基于它的实现做成线程安全并不冲突，只是会至少多一点缓存同步开销。

之前只在id分配和 ```task_manager``` 加了多线程单元测试。刚刚按我之前的描述方式加了直接用 ```task``` 接口的单元测试。代码见 ：https://github.com/owt5008137/libcopp/blob/v2/test/case/coroutine_task_test.cpp#L689

运行结果可以看 CI系统的输出log，如Linux下GCC 9环境的结果:  https://travis-ci.org/owt5008137/libcopp/jobs/610777308

然后里面搜索 ```Coroutine tasks are run on``` 。
比如我本地测试的时候的log

```bash
[ RUN      ] coroutine_task.mt_run_competition
[ RUNNING  ] Coroutine tasks are run on 77 threads at most.
[       OK ] coroutine_task.mt_run_competition (7687.5 ms)
```

这个是说单元测试里的切换线程最多的协程在77个线程中执行过。

**Comment by bigbao9494** [comment]
@owt5008137 感谢，因为我对整个代码不熟悉
“按boost.context的实现来说，它本身是不提供线程安全的功能的。但是基于它的实现做成线程安全并不冲突，只是会至少多一点缓存同步开销。"
具体实现我差异是体现在代码的哪个位置？因为我看到  fcontext/asm/ 中的文件和boost没有区别啊？
谢谢。

**Comment by owt5008137** [comment]
@bigbao9494 我不是在fcontext层实现线程安全的。

部分线程安全的处理分别在

+ coroutine_context (无锁): https://github.com/owt5008137/libcopp/blob/e3927a6f8433bcf3f44b5b2d55094004e901780a/src/libcopp/coroutine/coroutine_context.cpp#L311
+ task(无锁): https://github.com/owt5008137/libcopp/blob/e3927a6f8433bcf3f44b5b2d55094004e901780a/include/libcotask/task.h#L489
+ task_manager(自旋锁) : https://github.com/owt5008137/libcopp/blob/e3927a6f8433bcf3f44b5b2d55094004e901780a/include/libcotask/task_manager.h#L398
