### ISSUE TITLE
VS2013 的 std::atomic 实现发现了什么问题呢？

### ISSUE THREAD

**Issue by kwhitestone** [owt5008137/libcopp#9]
VS2013 的 std::atomic 实现发现了什么问题？ 为什么需要使用 InterlockedExchange 去重新实现？

**Comment by owt5008137** [comment]
@kwhitestone 实现不完整，编译有问题

**Comment by kwhitestone** [comment]
我尝试了一下是编译可以的 ， 所以想了解下是否碰到了奇怪的BUG

**Comment by owt5008137** [comment]
@kwhitestone 起源是其他项目碰到了VC 12（VS2013）里用它的std::atomic跑单元测试的时候会死锁。那个项目修订完以后一起移植过来的。

那个项目的提交在 https://github.com/atframework/atframe_utils/commit/13a77cc20b6463a2141268c200cd56c6f574b780
单元测试在: https://ci.appveyor.com/project/owt5008137/atframe-utils/builds/21245325

可能和 https://devblogs.microsoft.com/cppblog/stl-fixes-in-vs-2015-part-2/ 这里面修复的问题类似。
